PatschreiberCom::Application.routes.draw do
  get 'career/mission_statement'
  get 'career/resume'
  # The priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'
  root 'landing_page#index'

  get '/contact' => 'contact#index', :as => :contact
  # get '/resume' => 'contact#resume', :as => :resume

  scope '/hobbies' do
    get '/music' => 'hobby#music', :as => :music_hobby
  end

  scope 'career' do
    get '/cv' => 'career#resume', as: :resume
  end

  scope '/docs' do
    get '/api' => 'documentation#api_index', :as => :api_documentation
  end

  scope '/open-source' do
    get '/' => 'projects#open_source_index', :as => :open_source_index
    # The show method uses pretty URLs generated by friendly_id
    get '/:id' => 'projects#open_source_show', :as => :open_source_project
  end

  # Require json for the API
  namespace :api, constraints: lambda { |req| req.format == :json } do
    get '/cv' => 'cv#index', as: :cv_api
    get '/projects' => 'projects#index', as: :projects_api
  end
end
